package ftl

import (
	"database/sql"
	"time"
)

// Id is the Query identifier generated by Pihole and
type Id = int64

// Query record logged by FTL
type Query struct {
	Id           Id            `line:"-"`
	Timestamp    time.Time     `line:"time"`
	Type         Type          `line:"tag:Type"`
	Decision     Decision      `line:"tag:Decision"`
	Reason       Reason        `line:"tag:Reason"`
	Domain       string        `line:"tag:Domain"`
	Client       string        `line:"tag:Client"`
	Forward      string        `line:"tag:Forward"`
	ReplyType    ReplyType     `line:"tag:ReplyType"`
	ReplyTime    time.Duration `line:"field:ReplyTime"`
	DnsSecStatus DnsSecStatus  `line:"tag:DnsSecStatus"`
}

func ScanQuery(row *sql.Rows, query *Query) error {
	return row.Scan(
		&query.Id,
		ScanTimestamp(query),
		ScanType(query),
		ScanStatus(query),
		&query.Domain,
		&query.Client,
		ScanForward(query),
		ScanReplyType(query),
		ScanReplyTime(query),
		ScanDnsSec(query))
}
